import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BootstrapClient from "../../components/BootstrapClient";
import "animate.css";
import "./globals.scss";
import NavbarItem from "../../components/Navbars/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarItem />
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
